---
- name: Installer Wazuh Indexer
  hosts: indexer
  become: true
  vars:
    certs_dir: /etc/wazuh-indexer/certs
    local_archive_path: ./wazuh-certificates.tar
    remote_archive_path: /root/wazuh-certificates.tar
    certs_archive: /root/wazuh-certificates.tar  # adapte ce chemin si besoin
    node_name: "{{ ansible_hostname }}"  # ou bien une variable personnalisée si nécessaire
    
  tasks:
    - name: Sauvegarder le fichier opensearch.yml en opensearch.yml.bkp
      command: "mv /etc/wazuh-indexer/opensearch.yml /etc/wazuh-indexer/opensearch.yml.bkp"

    - name: Déployer le fichier indexer.yml avec le nom d'hôte dynamique
      template:
        src: opensearch.j2
        dest: /etc/wazuh-indexer/opensearch.yml
        owner: wazuh-indexer
        group: wazuh-indexer
        mode: '0644'

    - name: Copier l'archive wazuh-certificates.tar sur la machine cible
      copy:
        src: "{{ local_archive_path }}"
        dest: "{{ remote_archive_path }}"
        mode: '0644'
        
    - name: Exécuter un script avec une variable d'environnement
      shell: "export NODE_NAME={{ ansible_hostname }}"
        
    - name: Créer le dossier des certificats
      file:
        path: "{{ certs_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Extraire les certificats depuis l'archive
      ansible.builtin.command: >
        tar -xf {{ certs_archive }}
        -C {{ certs_dir }}
        ./{{ node_name }}.pem
        ./{{ node_name }}-key.pem
        ./admin.pem
        ./admin-key.pem
        ./root-ca.pem
      args:
        creates: "{{ certs_dir }}/{{ node_name }}.pem"

    - name: Renommer le certificat en indexer.pem
      command: >
        mv -n {{ certs_dir }}/{{ node_name }}.pem {{ certs_dir }}/indexer.pem
      args:
        creates: "{{ certs_dir }}/indexer.pem"

    - name: Renommer la clé privée en indexer-key.pem
      command: >
        mv -n {{ certs_dir }}/{{ node_name }}-key.pem {{ certs_dir }}/indexer-key.pem
      args:
        creates: "{{ certs_dir }}/indexer-key.pem"

    - name: Appliquer chmod 500 sur le dossier
      file:
        path: "{{ certs_dir }}"
        mode: '0500'
        recurse: yes

    - name: Appliquer chmod 400 sur tous les fichiers du dossier
      file:
        path: "{{ certs_dir }}/*"
        mode: '0400'
        recurse: yes

    - name: Appliquer ownership wazuh-indexer:wazuh-indexer
      file:
        path: "{{ certs_dir }}"
        owner: wazuh-indexer
        group: wazuh-indexer
        recurse: yes

    - name: Activer et Démarrer le service wazuh-indexer
      service:
        name: wazuh-indexer
        state: started
        enabled: true
